config/routes.rb
Ryokin::Application.routes.draw do

  get "advisors/add_comment" => "advisors#add_comment"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  resources :categories

  resources :rate_types

  resources :rates

  resources :banks
  
  resources :dashboards
  
  resources :advisors 
  
  resources :tips
  

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  belongs_to :bank
  belongs_to :advisor_type
  has_many :tips
  #has_and_belongs_to_many :advisor_qualities
  acts_as_commentable
  acts_as_rateable

  validates_presence_of :lastname
  validates_presence_of :firstname
  
end

app/models/advisor_type.rb
class AdvisorType < ActiveRecord::Base
  has_many :advisors
end

app/models/bank.rb
class Bank < ActiveRecord::Base
    has_many :rates
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_rate_types
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  
  
  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :bank
  belongs_to :category_rate_type
  has_one :rate_type, :through => :category_rate_type
  has_one :category, :through => :category_rate_type
  
  validates_presence_of :percent_rate
  
  
  
end

app/models/rate_type.rb
class RateType < ActiveRecord::Base
  has_many :category_rate_types
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  belongs_to :advisor
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
end

app/controllers/rate_types_controller.rb
class RateTypesController < ApplicationController
  # GET /rate_types
  # GET /rate_types.xml
  def index
    @rate_types = RateType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rate_types }
    end
  end

  # GET /rate_types/1
  # GET /rate_types/1.xml
  def show
    @rate_type = RateType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rate_type }
    end
  end

  # GET /rate_types/new
  # GET /rate_types/new.xml
  def new
    @rate_type = RateType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rate_type }
    end
  end

  # GET /rate_types/1/edit
  def edit
    @rate_type = RateType.find(params[:id])
  end

  # POST /rate_types
  # POST /rate_types.xml
  def create
    @rate_type = RateType.new(params[:rate_type])

    respond_to do |format|
      if @rate_type.save
        format.html { redirect_to(@rate_type, :notice => 'Rate type was successfully created.') }
        format.xml  { render :xml => @rate_type, :status => :created, :location => @rate_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rate_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rate_types/1
  # PUT /rate_types/1.xml
  def update
    @rate_type = RateType.find(params[:id])

    respond_to do |format|
      if @rate_type.update_attributes(params[:rate_type])
        format.html { redirect_to(@rate_type, :notice => 'Rate type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rate_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rate_types/1
  # DELETE /rate_types/1.xml
  def destroy
    @rate_type = RateType.find(params[:id])
    @rate_type.destroy

    respond_to do |format|
      format.html { redirect_to(rate_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
  
  def show_stars(nb)
    nb.times do
      image_tag "star.png"
    end
  end
  
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  
  def showSeries(arr)
    str = ""
    str += "series: ["
    
    arr.each do |bankname, percent|
      str += "{
		  name: '#{bankname}',
			data: 
			 #{percent.inspect}      			
			},"
    end
    str += "]"      
  end  
  
  def getRatesByBank()
    arr = {}    
    rates_arr = []
    old_bid = 0
    
    rates = Rate.all()
    rates.each do |r|
      if r.bank_id != old_bid
        rates_arr = []
      end
      old_bid = r.bank_id
      
      arr[r.bank.name] = rates_arr.push(r.percent_rate.to_f)
    end
    
    showSeries(arr)    
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rate_types_helper.rb
module RateTypesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tips_helper.rb
module TipsHelper
  
  def listip
    Tip.find(:last)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rate_types/_form.html.erb
<%= form_for(@rate_type) do |f| %>
  <% if @rate_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rate_type.errors.count, "error") %> prohibited this rate_type from being saved:</h2>

      <ul>
      <% @rate_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :nb_month %><br />
    <%= f.text_field :nb_month %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rate_types/edit.html.erb
<h1>Editing rate_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @rate_type %> |
<%= link_to 'Back', rate_types_path %>

app/views/rate_types/index.html.erb
<h1>Listing rate_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Nb month</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rate_types.each do |rate_type| %>
  <tr>
    <td><%= rate_type.name %></td>
    <td><%= rate_type.nb_month %></td>
    <td><%= link_to 'Show', rate_type %></td>
    <td><%= link_to 'Edit', edit_rate_type_path(rate_type) %></td>
    <td><%= link_to 'Destroy', rate_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rate type', new_rate_type_path %>

app/views/rate_types/new.html.erb
<h1>New rate_type</h1>

<%= render 'form' %>

<%= link_to 'Back', rate_types_path %>

app/views/rate_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rate_type.name %>
</p>

<p>
  <b>Nb month:</b>
  <%= @rate_type.nb_month %>
</p>


<%= link_to 'Edit', edit_rate_type_path(@rate_type) %> |
<%= link_to 'Back', rate_types_path %>