config/routes.rb
Ryokin::Application.routes.draw do

  get "advisors/add_comment" => "advisors#add_comment"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  resources :categories

  resources :rate_types

  resources :rates

  resources :banks
  
  resources :dashboards
  
  resources :advisors 
  
  resources :tips
  

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  belongs_to :bank
  belongs_to :advisor_type
  has_many :tips
  #has_and_belongs_to_many :advisor_qualities
  acts_as_commentable
  acts_as_rateable

  validates_presence_of :lastname
  validates_presence_of :firstname
  
end

app/models/advisor_type.rb
class AdvisorType < ActiveRecord::Base
  has_many :advisors
end

app/models/bank.rb
class Bank < ActiveRecord::Base
    has_many :rates
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_rate_types
end

app/models/category_rate_type.rb
class CategoryRateType < ActiveRecord::Base
  has_many :rates
  belongs_to :category
  belongs_to :rate_type
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  
  
  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :bank
  belongs_to :category_rate_type
  has_one :rate_type, :through => :category_rate_type
  has_one :category, :through => :category_rate_type
  
  validates_presence_of :percent_rate
  
  
  
end

app/models/rate_type.rb
class RateType < ActiveRecord::Base
  has_many :category_rate_types
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  belongs_to :advisor
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  respond_to :html, :xml, :json
  def index
    @advisors = Advisor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @advisor }
    end
  end
  
  def show
    @advisor = Advisor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @advisor }
    end
  end
  
  def edit
    @advisor = Advisor.find(params[:id])
    
  end
  
  def new
    @advisor = Advisor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @advisor }
    end
  end
  
  def add_comment
    @advisor = Advisor.find(params[:commentable_id])
    body_comment = params[:comment]
    
    @comment = @advisor.comments.new( :title => "Title comment", :comment => body_comment, :user => current_user)
    
    if @comment.save
      respond_with do |format|
        format.html do
          if request.xhr?
            #redirect_to root_url
          else
            redirect_to root_url, :notice => "Comment added for #{@advisor.firstname}!"          
          end
        end
      end
    end
  end
  
  def create
    @advisor = Advisor.new(params[:advisor])
    
    respond_to do |format|
      if @advisor.save
        format.html { redirect_to(@advisor, :notice => 'Advisor was successfully created.') }
        format.xml  { render :xml => @advisor, :status => :created, :location => @advisor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @advisor.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    @advisor = Advisor.find(params[:id])

    respond do |format|
      if @advisor.update_attributes(params[:rate])
        format.html { redirect_to(@advisor, :notice => 'Advisor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @advisor.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @advisor = Advisor.find(params[:id])
    @advisor.destroy

    respond_to do |format|
      format.html { redirect_to(advisors_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
  
  def show_stars(nb)
    nb.times do
      image_tag "star.png"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  
  def showSeries(arr)
    str = ""
    str += "series: ["
    
    arr.each do |bankname, percent|
      str += "{
		  name: '#{bankname}',
			data: 
			 #{percent.inspect}      			
			},"
    end
    str += "]"      
  end  
  
  def getRatesByBank()
    arr = {}    
    rates_arr = []
    old_bid = 0
    
    rates = Rate.all()
    rates.each do |r|
      if r.bank_id != old_bid
        rates_arr = []
      end
      old_bid = r.bank_id
      
      arr[r.bank.name] = rates_arr.push(r.percent_rate.to_f)
    end
    
    showSeries(arr)    
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rate_types_helper.rb
module RateTypesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tips_helper.rb
module TipsHelper
  
  def listip
    Tip.find(:last)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/advisors/_form.html.haml
= form_for @advisor do |f|
  - if @advisor.errors.any?
    %section#alerts
      .row
        .span16.columns
          .alert-message.error
            %a.close
              x
            %p
              %strong
                = pluralize(@advisor.errors.count, "error")
                prohibited this advisor from being saved:
              - @advisor.errors.full_messages.each do |msg|
                %p
                  = msg
          

  .field.clearfix
    = f.label :advisor_type_id
    .input
      = collection_select :advisor, :advisor_type_id, AdvisorType.find(:all), :id, :name

  .field.clearfix
    = f.label :bank_id
    .input
      = collection_select :advisor, :bank_id, Bank.find(:all), :id, :name

  .field.clearfix
    = f.label :lastname
    .input
      = f.text_field :lastname
  
  .field.clearfix
    = f.label :firstname
    .input
      = f.text_field :firstname


  .actions
    = f.submit :class => 'btn primary'

app/views/advisors/_listadvisors.html.haml
.page-header
	%h1 Advisors

.row
	.span16
		%ul#advisors_list
			- @advisors = Advisor.all
			- @advisors.each do |advisor|				
				%li					
					%span.advisor_name
						= link_to advisor.lastname + " " + advisor.firstname, advisor
						%span.bank_name
							= " from " + Bank.find(advisor.bank).name
					%span.advisor_rate
						- (advisor.average_rating_round).times do
							= image_tag "star.png"
					%span.view_comment{:class => 'pull-right'}
						- comments = advisor.comments.recent.limit(10).all
						= "View comments ( #{comments.count} )"
					.advisor_comments
						%ul
							- comments.each do |comment|
								%li
									= comment.comment
						%a{:class => 'btn primary pull-right btnAddComment', :id => 'advisor_click_'+advisor.id.to_s}
							= "Add comments"
						.clearfix

= render 'shared/comments', :locals => @advisors

app/views/advisors/edit.html.haml
%h1
  Edit Advisor
  
= render 'form'

= link_to 'Back', rates_path

app/views/advisors/new.html.haml
%h1
  New Advisor
  
= render 'form'

= link_to 'Back', root_path

app/views/advisors/show.html.haml
%section#advisor
  .page-header
    %h1      
      = @advisor.lastname + ', ' + @advisor.firstname
      %small 
        = AdvisorType.find(@advisor.advisor_type).name
        %em
          at               
        = Bank.find(@advisor.bank).name
        
  .row
    .span4
      sidebar
    .span12
      main text
    
    .span16
      = link_to 'Edit', edit_advisor_path(@advisor)
      |
      = link_to 'Back', advisors_path