config/routes.rb
Ryokin::Application.routes.draw do

  get "advisors/add_comment" => "advisors#add_comment"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  resources :categories

  resources :rate_types

  resources :rates

  resources :banks
  
  resources :dashboards
  
  resources :advisors 
  
  resources :tips
  

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  belongs_to :bank
  belongs_to :advisor_type
  has_many :tips
  #has_and_belongs_to_many :advisor_qualities
  acts_as_commentable
  acts_as_rateable

  validates_presence_of :lastname
  validates_presence_of :firstname
  
end

app/models/advisor_type.rb
class AdvisorType < ActiveRecord::Base
  has_many :advisors
end

app/models/bank.rb
class Bank < ActiveRecord::Base
    has_many :rates
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_rate_types
end

app/models/category_rate_type.rb
class CategoryRateType < ActiveRecord::Base
  has_many :rates
  belongs_to :category
  belongs_to :rate_type
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  
  
  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :bank
  belongs_to :category_rate_type
  has_one :rate_type, :through => :category_rate_type
  has_one :category, :through => :category_rate_type
  
  validates_presence_of :percent_rate
  
  
  
end

app/models/rate_type.rb
class RateType < ActiveRecord::Base
  has_many :category_rate_types
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  belongs_to :advisor
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  # GET /rates
  # GET /rates.xml
  def index
    @rates = Rate.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rates }
    end
  end

  # GET /rates/1
  # GET /rates/1.xml
  def show
    @rate = Rate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rate }
    end
  end

  # GET /rates/new
  # GET /rates/new.xml
  def new
    @rate = Rate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rate }
    end
  end

  # GET /rates/1/edit
  def edit
    @rate = Rate.find(params[:id])
  end

  # POST /rates
  # POST /rates.xml
  def create
    @rate = Rate.new(params[:rate])

    respond_to do |format|
      if @rate.save
        format.html { redirect_to(@rate, :notice => 'Rate was successfully created.') }
        format.xml  { render :xml => @rate, :status => :created, :location => @rate }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rates/1
  # PUT /rates/1.xml
  def update
    @rate = Rate.find(params[:id])

    respond_to do |format|
      if @rate.update_attributes(params[:rate])
        format.html { redirect_to(@rate, :notice => 'Rate was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.xml
  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to(rates_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
  
  def show_stars(nb)
    nb.times do
      image_tag "star.png"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  
  def showSeries(arr)
    str = ""
    str += "series: ["
    
    arr.each do |bankname, percent|
      str += "{
		  name: '#{bankname}',
			data: 
			 #{percent.inspect}      			
			},"
    end
    str += "]"      
  end  
  
  def getRatesByBank()
    arr = {}    
    rates_arr = []
    old_bid = 0
    
    rates = Rate.all()
    rates.each do |r|
      if r.bank_id != old_bid
        rates_arr = []
      end
      old_bid = r.bank_id
      
      arr[r.bank.name] = rates_arr.push(r.percent_rate.to_f)
    end
    
    showSeries(arr)    
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rate_types_helper.rb
module RateTypesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tips_helper.rb
module TipsHelper
  
  def listip
    Tip.find(:last)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rates/_form.html.haml
= form_for @rate do |f|
  - if @rate.errors.any?
    %section#alerts
      .row
        .span16.columns
          .alert-message.error
            %a.close
              x
            %p
              %strong
                = pluralize(@rate.errors.count, "error")
                prohibited this rate from being saved:
              - @rate.errors.full_messages.each do |msg|
                %p
                  = msg
            
  .field.clearfix
    = f.label :bank_id
    .input
      = f.text_field :bank_id

  .field.clearfix
    = f.label :category_rate_type_id
    .input
      = f.text_field :category_rate_type_id

  .field.clearfix
    = f.label :percent_rate
    .input
      = f.text_field :percent_rate

  .actions
    = f.submit :class => 'btn primary'

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/edit.html.haml
%h1
  Editing rate

= render 'form'

= link_to 'Show', @rate 
= link_to 'Back', rates_path

app/views/rates/index.html.erb
<h1>Listing rates</h1>

<table>
  <tr>
    <th>Bank</th>
    <th>Category rate type</th>
    <th>Percent rate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rates.each do |rate| %>
  <tr>
    <td><%= rate.bank_id %></td>
    <td><%= rate.category_rate_type_id %></td>
    <td><%= rate.percent_rate %></td>
    <td><%= link_to 'Show', rate %></td>
    <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
    <td><%= link_to 'Destroy', rate, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rate', new_rate_path %>

app/views/rates/index.html.haml
%h1
  Listing rates

%table
  %thead
    %tr
      %th
        Bank
      %th
        Category rate type
      %th
      %th
      %th
      %th
  %tbody
    - @rates.each do |rate| 
      %tr
        %td
          = rate.bank_id
        %td
          = rate.category_rate_type_id
        %td
          = rate.percent_rate
        %td
          = link_to 'Show', rate
        %td
          = link_to 'Edit', edit_rate_path(rate)
        %td
          = link_to 'Destroy', rate, :confirm => 'Are you sure?', :method => :delete
        
%br
    
= link_to 'New Rate', new_rate_path, :class => "btn primary"

app/views/rates/new.html.haml
%h1
  New rate
  
= render 'form'

= link_to 'Back', rates_path

app/views/rates/show.html.haml
%p#notice
  = notice

%p
  %strong
    Bank:
    = @rate.bank_id

%p
  %strong
    Category rate type:
    = @rate.category_rate_type_id

%p
  %strong
    Percent rate:
    = @rate.percent_rate    
    
= link_to 'Edit', edit_rate_path(@rate)
|
= link_to 'Back', rates_path